name: Java CI with Maven

# 트리거 설정 (코드 푸시 및 PR 시 실행)
on:
  push:
    branches:
      - feature

# Job 정의
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11

    - name: Build with Maven
      env:
          API_KEY: ${{ secrets.API_KEY }}
      run: mvn clean install

    - name: Upload artifact 
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact  
        path: target/  

  test:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Run tests with Maven
        run: mvn test -f target/pom.xml  # 다운로드한 빌드 결과를 테스트
